var charizardHP= 78;
var charizardNum = 6;
var charizardType= "Fire";
var charizardBestMove=" Flame Thrower";
var charizardLastEvo= true;
var charizardCatchRatePercent= 0;
var charizardHeight="1.7 M";
var charizardWeight="90.5 kg";
var charizardPreEvolution= "Charmeleon";
var charizardSpeed= 100;
var venusaurHP= 80;
var venusaurNum = 3;
var venusaurType= "Grass";
var venusaurBestMove=" Solar Beam";
var venusaurLastEvo= true;
var venusaurCatchRatePercent= 0;
var venusaurHeight="2 M";
var venusaurWeight="100 kg";
var venusaurPreEvolution= "Ivysaur";
var venusaurSpeed= 80;
var blastoiseHP= 79;
var blastoiseNum = 9;
var blastoiseType= "Water";
var blastoiseBestMove=" Hydro Pump";
var blastoiseLastEvo= true;
var blastoiseCatchRatePercent= 0;
var blastoiseHeight="1.6 M";
var blastoiseWeight="85.5 kg";
var blastoisePreEvolution= "Wartortle";
var blastoiseSpeed= 78;
charizardHP= charizardHP - 50
venusaurHP= venusaurHP - 50
blastoiseHP= blastoiseHP - 50
console.log("YOUR POKEMON TOOK DAMAGE!")